# Project: pointer_example_1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = pointer_example_1.o pointer_example_1.o pointer_example_1.o
LINKOBJ  = pointer_example_1.o pointer_example_1.o pointer_example_1.o
LIBS     = -L"C:/Users/samsung/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/samsung/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/samsung/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/samsung/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/samsung/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/samsung/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/samsung/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/samsung/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/samsung/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = pointer_example_1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

pointer_example_1.o: pointer_example_1.c
	$(CC) -c pointer_example_1.c -o pointer_example_1.o $(CFLAGS)

pointer_example_1.o: pointer_example_1.cpp
	$(CC) -c pointer_example_1.cpp -o pointer_example_1.o $(CFLAGS)
